extras: Update extras/mpvc-installer

diff --git a/extras/mpvc-installer b/extras/mpvc-installer
--- a/extras/mpvc-installer
+++ b/extras/mpvc-installer
@@ -152,7 +152,7 @@ mpvc_check_requirements()
     # attempt at listing packages required by mpvc & extras/ to work
     echo "# Checking required deps:"
     for cmd in sh mpv fzf socat awk sed; do
-        command -v "$cmd" | sed 's/^/  /' || echo "$PROGNAME: Error: No $cmd found. Install to continue"
+        (command -v "$cmd" || echo "$PROGNAME: Error: No $cmd found. Install to continue") | sed 's/^/  /'
     done
     # recommened, and good to have, but not required
     echo "# Checking recommended deps:"
