extras: Update extras/mpvc-cut

diff --git a/extras/mpvc-cut b/extras/mpvc-cut
--- a/extras/mpvc-cut
+++ b/extras/mpvc-cut
@@ -14,9 +14,12 @@ PROGURL="https://github.com/gmt4/mpvc"
 
 set -euf
 
+FFMPEG=$(command -v ffmpeg) || { echo "ffmpeg not found"; exit 1; }
+FFPROBE=$(command -v ffprobe) || { echo "ffprobe not found"; exit 1; }
+
 mpvc_cut_ffmpeg()
 {
-    ffmpeg -hide_banner -loglevel "$LOGLEVEL" -i "$path" -ss "$pointA" -to "$pointB" "$@"
+    "$FFMPEG" -hide_banner -loglevel "$LOGLEVEL" -i "$path" -ss "$pointA" -to "$pointB" -- "$@"
 }
 
 mpvc_cutfile()
@@ -26,14 +29,14 @@ mpvc_cutfile()
     pointA="$3"
     pointB="$4"
 
-    if [ -z "$path" ] || [ ! -e "$path" ]; then usage 1; fi
+    if [ -z "$path" ] || [ ! -f "$path" ]; then usage 1; fi
     if [ -z "$pointA" ] || [ "$pointA" = "no" ]; then usage 1; fi
     if [ -z "$pointB" ] || [ "$pointB" = "no" ]; then pointB="$(mpvc -f "%length%")"; fi
 
     fileExt="${path#*.}"
     infile="${path##*/}"
     infile="${infile##"$fileExt"}"
-    outfile="${outfile:-$infile.$pointA.$pointB}"
+    outfile="${outfile:-${infile}_${pointA}_${pointB}}"
     LOGLEVEL=${LOGLEVEL:-warning}
 
     echo "# $PROGNAME $operation $pointA $pointB $fileExt in $infile out $outfile"
@@ -60,7 +63,7 @@ mpvc_cut()
 
 mpvc_cut_vres()
 {
-    xrandr | awk '
+    $(command -v xrandr) | awk '
         /^Screen 0: .* current .*/ {
             r=$0; sub("^.* current ","",r); sub(", maximum .*$","",r); gsub(" ","",r); print r; exit
         }'
@@ -69,7 +72,7 @@ mpvc_cut_vres()
 mpvc_cut_info()
 {
     mode=$1; shift
-    ffprobe -hide_banner -loglevel info "$@" 2>&1 |
+    "$FFPROBE" -hide_banner -loglevel info "$@" 2>&1 |
         case "$mode" in
         info) awk '/^Input/ {print} /Stream #/ {print} /Duration:/ {print}' ;;
         Info) awk '{print}' ;;
@@ -100,7 +103,7 @@ mpvc_screencast()
     if [ -z "$asrc" ]; then usage; fi
 
     echo "# $PROGNAME: recording vres $vres asrc $asrc to $fout (ctl+c to finish)"
-    ffmpeg -hide_banner -loglevel "$LOGLEVEL" -video_size "$vres" -framerate "$framerate" -f x11grab -i :0.0 -f pulse -ac 2 -i "$asrc" "$fout"
+    "$FFMPEG" -hide_banner -loglevel "$LOGLEVEL" -video_size "$vres" -framerate "$framerate" -f x11grab -i :0.0 -f pulse -ac 2 -i "$asrc" "$fout"
 }
 
 usage()
